/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controller;
import Modelo.Clases.Producto;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankar
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPaneTienda = new javax.swing.JTabbedPane();
        PanelRegistrar = new javax.swing.JPanel();
        ButtonGuardar = new javax.swing.JButton();
        LabelRegistrarNombre = new javax.swing.JLabel();
        LabelRegistrarCantidad = new javax.swing.JLabel();
        LabelPrecio = new javax.swing.JLabel();
        LabelCategoria = new javax.swing.JLabel();
        TextFieldRegistrarNombre = new javax.swing.JTextField();
        TextFieldRegistrarCantidad = new javax.swing.JTextField();
        TextFieldRegistrarPrecio = new javax.swing.JTextField();
        ComboBoxCategoria = new javax.swing.JComboBox<>();
        LabelRta = new javax.swing.JLabel();
        PanelConsultar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDB = new javax.swing.JTable();
        LabelIDConsultar = new javax.swing.JLabel();
        LabelNombreConsultar = new javax.swing.JLabel();
        LabelCantidadConsultar = new javax.swing.JLabel();
        LabelPrecioConsultar = new javax.swing.JLabel();
        LabelCategoriaConsultar = new javax.swing.JLabel();
        ComboBoxCategoriaConsultar = new javax.swing.JComboBox<>();
        TextFieldCantidadConsultar = new javax.swing.JTextField();
        TextFieldPrecioConsultar = new javax.swing.JTextField();
        TextFieldIDConsultar = new javax.swing.JTextField();
        TextFieldNombreConsultar = new javax.swing.JTextField();
        ButtonEliminarConsultar = new javax.swing.JButton();
        ButtonConsultarConsultar = new javax.swing.JButton();
        ButtonActualizarConsultar = new javax.swing.JButton();
        LabelRtaConsultar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonGuardar.setText("Guardar");
        ButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGuardarActionPerformed(evt);
            }
        });

        LabelRegistrarNombre.setText("Nombre");

        LabelRegistrarCantidad.setText("Cantidad");

        LabelPrecio.setText("Precio");

        LabelCategoria.setText("Categoria");

        ComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASEO", "VIVERES" }));
        ComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRegistrarLayout = new javax.swing.GroupLayout(PanelRegistrar);
        PanelRegistrar.setLayout(PanelRegistrarLayout);
        PanelRegistrarLayout.setHorizontalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistrarLayout.createSequentialGroup()
                        .addComponent(LabelRta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonGuardar))
                    .addGroup(PanelRegistrarLayout.createSequentialGroup()
                        .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelRegistrarNombre)
                            .addComponent(LabelRegistrarCantidad)
                            .addComponent(LabelPrecio)
                            .addComponent(LabelCategoria))
                        .addGap(77, 77, 77)
                        .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxCategoria, 0, 100, Short.MAX_VALUE)
                            .addComponent(TextFieldRegistrarPrecio)
                            .addComponent(TextFieldRegistrarCantidad)
                            .addComponent(TextFieldRegistrarNombre))
                        .addContainerGap(152, Short.MAX_VALUE))))
        );
        PanelRegistrarLayout.setVerticalGroup(
            PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistrarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRegistrarNombre)
                    .addComponent(TextFieldRegistrarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRegistrarCantidad)
                    .addComponent(TextFieldRegistrarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPrecio)
                    .addComponent(TextFieldRegistrarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCategoria)
                    .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(PanelRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonGuardar)
                    .addComponent(LabelRta)))
        );

        TabbedPaneTienda.addTab("Registrar", PanelRegistrar);

        TablaDB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoria", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDB);

        LabelIDConsultar.setText("ID");

        LabelNombreConsultar.setText("Nombre");

        LabelCantidadConsultar.setText("Cantidad");

        LabelPrecioConsultar.setText("Precio");

        LabelCategoriaConsultar.setText("Categoria");

        ComboBoxCategoriaConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASEO", "VIVERES" }));

        TextFieldNombreConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNombreConsultarActionPerformed(evt);
            }
        });

        ButtonEliminarConsultar.setText("Eliminar");
        ButtonEliminarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarConsultarActionPerformed(evt);
            }
        });

        ButtonConsultarConsultar.setText("Consultar");
        ButtonConsultarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConsultarConsultarActionPerformed(evt);
            }
        });

        ButtonActualizarConsultar.setText("Actualizar");
        ButtonActualizarConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActualizarConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelConsultarLayout = new javax.swing.GroupLayout(PanelConsultar);
        PanelConsultar.setLayout(PanelConsultarLayout);
        PanelConsultarLayout.setHorizontalGroup(
            PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCategoriaConsultar)
                    .addComponent(LabelIDConsultar)
                    .addComponent(LabelPrecioConsultar)
                    .addComponent(LabelCantidadConsultar)
                    .addComponent(LabelNombreConsultar))
                .addGap(59, 59, 59)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldIDConsultar)
                    .addComponent(TextFieldNombreConsultar)
                    .addComponent(TextFieldCantidadConsultar)
                    .addGroup(PanelConsultarLayout.createSequentialGroup()
                        .addComponent(ComboBoxCategoriaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addComponent(TextFieldPrecioConsultar))
                .addGap(27, 27, 27)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonEliminarConsultar)
                    .addComponent(ButtonActualizarConsultar)
                    .addComponent(ButtonConsultarConsultar))
                .addGap(44, 44, 44))
            .addComponent(LabelRtaConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelConsultarLayout.setVerticalGroup(
            PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelRtaConsultar)
                .addGap(5, 5, 5)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDConsultar)
                    .addComponent(TextFieldIDConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonEliminarConsultar))
                .addGap(26, 26, 26)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNombreConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonConsultarConsultar)
                    .addComponent(LabelNombreConsultar))
                .addGap(18, 18, 18)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCantidadConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonActualizarConsultar)
                    .addComponent(LabelCantidadConsultar))
                .addGap(18, 18, 18)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPrecioConsultar)
                    .addComponent(TextFieldPrecioConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCategoriaConsultar)
                    .addComponent(ComboBoxCategoriaConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        TabbedPaneTienda.addTab("Consultar", PanelConsultar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneTienda)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneTienda)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCategoriaActionPerformed

    }//GEN-LAST:event_ComboBoxCategoriaActionPerformed

    private void ButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGuardarActionPerformed
        this.LabelRta.setText("");
        String nombre = this.TextFieldRegistrarNombre.getText();
        String cantidad = this.TextFieldRegistrarCantidad.getText();
        String categoria = this.ComboBoxCategoria.getSelectedItem().toString();
        String precio = this.TextFieldRegistrarPrecio.getText();
        if (nombre.length() == 0
                || cantidad.length() == 0
                || precio.length() == 0
            ) {
            this.LabelRta.setText("Ingrese valores validos");
        } else {
            try {
                Controller.registrarProducto(nombre, Integer.valueOf(cantidad), categoria, Double.valueOf(precio));
                this.LabelRta.setText("Producto registrado con exito");
                this.TextFieldRegistrarCantidad.setText(null);
                this.TextFieldRegistrarNombre.setText(null);
                this.TextFieldRegistrarPrecio.setText(null);
            } catch (SQLException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                this.LabelRta.setText("Producto no registrado. ERROR");
            }
        }
    }//GEN-LAST:event_ButtonGuardarActionPerformed

    private void TextFieldNombreConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNombreConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNombreConsultarActionPerformed
    
    private void ButtonConsultarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConsultarConsultarActionPerformed
        String idString = this.TextFieldIDConsultar.getText();
        DefaultTableModel modelo = (DefaultTableModel) this.TablaDB.getModel();
        modelo.setRowCount(0);
        if (idString.length() == 0) {
            List<Producto> listaproductos = Controller.listarProductos();
            for (int i = 0; i < listaproductos.size(); i++) {
                Producto pr = listaproductos.get(i);
                modelo.insertRow(
                        i, new Object[]{
                            pr.getID(), pr.getNombre(), pr.getCategoria(),
                            pr.getCantidad(), pr.getPrecio()
                        }
                );
            }

        } else {
            Producto pro = Controller.obtenerProducto(Integer.valueOf(idString));
            modelo.insertRow(
                    0, new Object[]{
                        pro.getID(), pro.getNombre(), pro.getCategoria(),
                        pro.getCantidad(), pro.getPrecio()
                    }
            );
        }

    }//GEN-LAST:event_ButtonConsultarConsultarActionPerformed

    private void TablaDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDBMouseClicked
        JTable table = (JTable) evt.getSource();
        int row = table.rowAtPoint(evt.getPoint());
        DefaultTableModel model = (DefaultTableModel) this.TablaDB.getModel();
        String ID = String.valueOf(model.getValueAt(row, 0));
        String Nombre = String.valueOf(model.getValueAt(row, 1));
        String Categoria = String.valueOf(model.getValueAt(row, 2));
        String Cantidad = String.valueOf(model.getValueAt(row, 3));
        String Precio = String.valueOf(model.getValueAt(row, 4));
        
        this.TextFieldIDConsultar.setText(ID);
        this.TextFieldNombreConsultar.setText(Nombre);
        this.TextFieldPrecioConsultar.setText(Precio);
        this.TextFieldCantidadConsultar.setText(Cantidad);
        this.ComboBoxCategoriaConsultar.setSelectedItem(Categoria);
    }//GEN-LAST:event_TablaDBMouseClicked

    private void ButtonEliminarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarConsultarActionPerformed
        String ID = this.TextFieldIDConsultar.getText();
        if (ID.length() == 0)
        {
            this.LabelRtaConsultar.setText("Ingrese datos validos");
        }else{
            Controller.borrarProducto(Integer.valueOf(ID));
            this.LabelRtaConsultar.setText("Eliminacion Exitosa!");
        }
        this.TextFieldCantidadConsultar.setText(null);
        this.TextFieldNombreConsultar.setText(null);
        this.TextFieldPrecioConsultar.setText(null);
        this.TextFieldIDConsultar.setText(null);
    }//GEN-LAST:event_ButtonEliminarConsultarActionPerformed

    private void ButtonActualizarConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActualizarConsultarActionPerformed
        String ID = this.TextFieldIDConsultar.getText();
        String nombre = this.TextFieldNombreConsultar.getText();
        String precio = this.TextFieldPrecioConsultar.getText();
        String cantidad = this.TextFieldCantidadConsultar.getText();
        String categoria = this.ComboBoxCategoriaConsultar.getSelectedItem().toString();
         if (nombre.length() == 0
                || cantidad.length() == 0
                || precio.length() == 0
                || ID.length() == 0
            ) {
            this.LabelRtaConsultar.setText("Ingrese valores validos");
         } else{
            Controller.actualizarProducto(Integer.valueOf(ID), nombre, Integer.valueOf(cantidad), categoria, Double.valueOf(precio));
            this.LabelRtaConsultar.setText("Actualizacion Exitosa!");
            this.TextFieldCantidadConsultar.setText(null);
            this.TextFieldNombreConsultar.setText(null);
            this.TextFieldPrecioConsultar.setText(null);
            this.TextFieldIDConsultar.setText(null);
         }
    }//GEN-LAST:event_ButtonActualizarConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonActualizarConsultar;
    private javax.swing.JButton ButtonConsultarConsultar;
    private javax.swing.JButton ButtonEliminarConsultar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JComboBox<String> ComboBoxCategoria;
    private javax.swing.JComboBox<String> ComboBoxCategoriaConsultar;
    private javax.swing.JLabel LabelCantidadConsultar;
    private javax.swing.JLabel LabelCategoria;
    private javax.swing.JLabel LabelCategoriaConsultar;
    private javax.swing.JLabel LabelIDConsultar;
    private javax.swing.JLabel LabelNombreConsultar;
    private javax.swing.JLabel LabelPrecio;
    private javax.swing.JLabel LabelPrecioConsultar;
    private javax.swing.JLabel LabelRegistrarCantidad;
    private javax.swing.JLabel LabelRegistrarNombre;
    private javax.swing.JLabel LabelRta;
    private javax.swing.JLabel LabelRtaConsultar;
    private javax.swing.JPanel PanelConsultar;
    private javax.swing.JPanel PanelRegistrar;
    private javax.swing.JTabbedPane TabbedPaneTienda;
    private javax.swing.JTable TablaDB;
    private javax.swing.JTextField TextFieldCantidadConsultar;
    private javax.swing.JTextField TextFieldIDConsultar;
    private javax.swing.JTextField TextFieldNombreConsultar;
    private javax.swing.JTextField TextFieldPrecioConsultar;
    private javax.swing.JTextField TextFieldRegistrarCantidad;
    private javax.swing.JTextField TextFieldRegistrarNombre;
    private javax.swing.JTextField TextFieldRegistrarPrecio;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
